openapi: 3.0.1
info:
  title: codeGenerationService
  description: APIs for generating and managing API codes from specifications
  version: 1.0.0
servers:
  - url: https://virtserver.swaggerhub.com/BIAN-3/BIAN/CodeGeneration/1.0.0
paths:
  "/codeGenerationService/GenerateAPICode/Initiate":
    post:
      tags: [CR - Generation]
      summary: Generate API code
      description: Initiate API code generation from specification
      operationId: InitiateCodeGeneration
      requestBody:
        $ref: "#/components/requestBodies/InitiateGenerationRequest"
      responses:
        "200":
          $ref: "#/components/responses/InitiateGenerationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
  "/codeGenerationService/GeneratedCode/Retrieve":
    get:
      tags: [CR - GeneratedCode]
      summary: Retrieve generated codes
      description: Retrieve previously generated API codes
      operationId: RetrieveGeneratedCode
      responses:
        "200":
          $ref: "#/components/responses/RetrieveGeneratedCodeResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    GenerationRequest:
      type: object
      properties:
        specification:
          type: string
          description: API specification in OpenAPI/YAML format
        targetLanguage:
          type: string
          enum: [JavaScript, TypeScript, Python, Java, C#, Go, PHP, Ruby]
          description: Target programming language for code generation
        framework:
          type: string
          enum: [Express, Flask, Spring, Django, Laravel, Rails, Gin, Fiber]
          description: Target framework for code generation
        options:
          type: object
          properties:
            includeTests:
              type: boolean
              description: Whether to include test files
            includeDocs:
              type: boolean
              description: Whether to include documentation
            useESLint:
              type: boolean
              description: Whether to include ESLint configuration (for JS/TS)
            usePrettier:
              type: boolean
              description: Whether to include Prettier configuration (for JS/TS)
    GeneratedCode:
      type: object
      properties:
        generationId:
          type: string
          description: Unique identifier for this generation
        status:
          type: string
          enum: [Pending, Completed, Failed]
          description: Status of the generation process
        downloadUrl:
          type: string
          description: URL to download the generated code
        createdAt:
          type: string
          format: date-time
          description: When the code was generated
        language:
          type: string
          description: Target language of the generated code
        framework:
          type: string
          description: Framework used in the generated code
        specificationVersion:
          type: string
          description: Version of the input specification
    InitiateGenerationRequest:
      type: object
      properties:
        generationRequest:
          $ref: "#/components/schemas/GenerationRequest"
    RetrieveGeneratedCodeResponse:
      type: object
      properties:
        generatedCodes:
            $ref: "#/components/schemas/GeneratedCode"
    InitiateGenerationResponse:
      type: object
      properties:
        generation:
          $ref: "#/components/schemas/GeneratedCode"
    HTTPError:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: integer
          format: int32
          description: HTTP status code
        details:
          type: string
          description: Additional error details
  requestBodies:
    InitiateGenerationRequest:
      description: Request to generate API code
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InitiateGenerationRequest"
      required: true
  responses:
    InitiateGenerationResponse:
      description: Response for code generation initiation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InitiateGenerationResponse"
    RetrieveGeneratedCodeResponse:
      description: Response containing generated codes
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RetrieveGeneratedCodeResponse"
    BadRequest:
      description: Bad request error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    Unauthorized:
      description: Unauthorized error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    Forbidden:
      description: Forbidden error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    NotFound:
      description: Not found error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    TooManyRequests:
      description: Too many requests error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    InternalServerError:
      description: Internal server error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
